name: Lint Commit Messages

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.6.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Dependencies
        run: yarn --immutable

      - uses: wagoid/commitlint-github-action@v4
