name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master, dev]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.1.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run Linter
        run: yarn lerna run lint:report
        continue-on-error: true

  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.1.0]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get Yarn Cache Directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Restore Yarn Cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn --immutable

      - name: Run Tests
        run: yarn lerna run test -- -- --coverage

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
