name: Publish

on:
  workflow_dispatch:

env:
  TURTLE_VERSION: 0.23.1
  EXPO_CLI_VERSION: 4.12.10
  EXPO_SDK_VERSION: 43.0.0
  EXPO_USERNAME: xenfo
  EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
  EXPO_IOS_DIST_P12_PASSWORD: ${{ secrets.EXPO_IOS_DIST_P12_PASSWORD }}
  EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
  EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.6.0]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Expo CLI
        uses: expo/expo-github-action@v7
        with:
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: ${{ env.EXPO_CLI_VERSION }}

      - name: Install Dependencies
        run: yarn --immutable

      - name: Publish App
        run: cd packages/app && expo publish

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [publish]

    strategy:
      matrix:
        node-version: [17.6.0]
        java-version: [8]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Decrypt Keystore
        run: gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DECRYPT_PASSWORD }}" --output ./.github/secrets/utils.jks ./.github/secrets/utils.jks.gpg

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: Install Expo CLI
        uses: expo/expo-github-action@v7
        with:
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: ${{ env.EXPO_CLI_VERSION }}

      - name: Restore Turtle Cache
        uses: actions/cache@v2
        id: turtle-cache
        with:
          path: ~/.turtle
          key: turtle-${{ runner.os }}-${{ env.EXPO_SDK_VERSION }}-android

      - name: Install Dependencies
        run: |
          npm i -g turtle-cli
          yarn --immutable

      - name: Setup Turtle
        run: turtle setup:android --sdk-version ${{ env.EXPO_SDK_VERSION }}

      - name: Build App
        run: |
          cd packages/app
          turtle build:android -t apk -o ../../utils.apk --keystore-path ../../.github/secrets/utils.jks --keystore-alias ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}

      - name: Upload APK
        run: aws s3 cp ./utils.apk s3://xenfo-utils/builds/android/${{ env.EXPO_SDK_VERSION }}/utils-${{ hashFiles('**/utils.apk') }}-signed.apk --acl public-read

      - name: Update API
        run: 'curl -H "x-api-key: ${{ secrets.UTILS_API_KEY }}" https://utils.xenfo.dev/api/android/update'
